import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
// Remove any pre-existing ORT singleton so transformers.js picks onnxruntime-web (wasm)
// instead of an externally registered backend that leaves supportedDevices empty.
delete globalThis[Symbol.for("onnxruntime")];
`;

const prod = (process.argv[2] === "production");

// onnxruntime-web's Oa() skips the bundled inline WASM factory (Aa) because
// import.meta.url is undefined in a CJS bundle (so Ue is never set). Without Ue
// it falls back to a CDN dynamic import() of the .jsep.mjs which spawns
// em-pthread workers — those workers attempt import('worker_threads'), which
// Chromium's ESM worker scope rejects with "Failed to resolve module specifier".
// Patching the guard to `if (Aa)` forces the already-bundled inline factory so
// no external module fetch or worker creation is needed.
const patchOnnxPlugin = {
  name: "patch-onnx-inline-wasm",
  setup(build) {
    build.onEnd(() => {
      const path = build.initialOptions.outfile;
      let src = fs.readFileSync(path, "utf8");
      const before = "if (!e && !t && Aa && Ue && Ln(Ue))";
      const after  = "if (Aa)";
      if (!src.includes(before)) {
        console.warn("[patch-onnx] guard string not found — skipping (bundle format may have changed)");
        return;
      }
      fs.writeFileSync(path, src.replace(before, after));
      console.log("[patch-onnx] patched Oa() → inline WASM factory always used");
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins
  ],
  format: "cjs",
  target: "es2020",
  // Electron renderer exposes process.release.name="node", which makes
  // @huggingface/transformers pick onnxruntime-node (unbundleable native
  // bindings). Patching it to "browser" forces onnxruntime-web (WASM).
  define: { "process.release.name": '"browser"' },
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins: [patchOnnxPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
