name: Biome check

on:
  push:
    branches: ["**"]
    paths:
      - "**.ts"
      - "**.css"
      - "**.jsonc?"
      - "**.m?js"
  pull_request:
    paths:
      - "**.ts"
      - "**.css"
      - "**.jsonc?"
      - "**.m?js"

jobs:
  biome-check:
    name: Biome check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: biomejs/setup-biome@v2
      - run: biome ci
